  - name: Install Start and Enable Apache by decision making in ansible
    hosts: group1
    tasks:
      - name: Start apache in Ubuntu
        ansible.builtin.apt:
          name: apache2
          state: present
        when: ansible_os_family == "Debian"
      - name: Enable and start apache2
        ansible.builtin.service:
          name: apache2
          enabled: yes
          state: started
        when: ansible_facts['os_family'] == "Debian" #Dictionary variable 
          # - ansible_os_family == "Debian"
      - name: Install service apache2 in Alma Linux
        ansible.builtin.dnf:
          name: httpd
          state: present
        when: ansible_facts['distribution_major_version'] == "9"
          #ansible_os_family == "RedHat"
      - name: Start and anable service apache2
        ansible.builtin.service:
          name: httpd
          enabled: yes
          state: started
        when: ansible_os_family == "RedHat"
