  - name: Install httpd, postgresql in node1 and nginx in node2
    hosts: node1
    tasks:
      - name: install httpd, postgresql in node1
        package:
          name: httpd,postgresql-server
          state: present
  - name: Install nginx
    hosts: node2
    tasks:
      - name: install nginx in node2
        package:
          name: nginx
          state: present

