#Declare a variable app_version with the value 1.0 in a playbook and use it in a task to create a file named app_version.txt with the content 1.0.
---
  - name: Declare a variable app_version with the value 1.0 
    hosts: node1
    vars:
      app_version: 1.0
    tasks:
      - name: 
        ansible.builtin.copy:
          dest: /home/bavin/app_version.txt
          content: "{{app_version}}"
        register: output
      - name: debug
        debug:
          var: output
...
