  - name: Use loop
    hosts: group1
    tasks:
      - name: Install using loop
        package:
          name: "{{item}}"
          state: present
        loop:
          - nginx
            #- mariadb
          - chrony
      - name:
        service:
          name: "{{item}}"
          enabled: yes
          state: started
        loop: 
            - nginx
            #- mariadb
            - chronyd
        register: output
          #  - name: Debug
          # debug:
          #var: output
