  - name: Install ntp in both ubuntu and Alma linux
    hosts: group1
    tasks:
      - name: Install ntp(chrony) in Alma linux
        ansible.builtin.package:
          name: chrony
          state: present
        when: ansible_distribution == "AlmaLinux"
        tags:                #tags is used to call a specific tasks from the 
          - alma
          - amla

      - name: Start and enable service chrony in Alma Linux
        ansible.builtin.service:
          name: chronyd
          enabled: yes
          state: started
        when: ansible_distribution == "AlmaLinux"
        tags:
          - alma
          - ntu

      - name: Install ntp in Ubuntu
        ansible.builtin.package:
          name: ntp
          state: present
        when: ansible_distribution == "Ubuntu"
        tags:
          - ubu
          - ntu

      - name: Start and enable service ntp in Ubuntu
        ansible.builtin.systemd:
          name: ntpd
          enabled: yes
          state: started
        when: ansible_distribution == "Ubuntu"
        tags:
          - ubu
          - alma
