  - name: Installing Postgresql and Starting the service
    hosts: group1
    tasks:
      - name: Installing Postgresql
        package:
          name: postgresql-server
          state: present
      - name: Starting service
        service:
          name: postgresql
          enabled: no
          state: stopped
