  - name: Variable in mariadb
    hosts: node1
    vars:
      name: tom  #this  is variable declaration you can use any variable as your choice
      user: jerry
      passd: 12
    tasks:
      - name: Install mariadb
        ansible.builtin.package:
          name: mariadb-server
          state: present
      - name: Start the service
        ansible.builtin.service:
          name: mariadb
          enabled: yes
          state: started
      - name: Install python
        ansible.builtin.package:
          name: python3-PyMySQL
          state: present
      - name: Create a database
        mysql_db:
          name: "{{name}}"
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
      - name: Create a user
        mysql_user:
          name: "{{user}}"
          password: "{{passd}}"
          priv: '*.*:ALL'
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
        register: output   # To register or view the details of the current task by calling in debug
      - name: Debug1
        debug:
          var: output
      - name: Debug2
        debug:
          var: user
      - name: Debug3
        debug:
          msg: "The database named {{name}} is created"
