  - name: Variable in mariadb
    hosts: node1
    vars:
      eman: bavindb   #this is variable declaration you can use any variable as your choice
      resu: bavin
      ssap: 123
    tasks:
      - name: Install mariadb
        ansible.builtin.package:
          name: mariadb-server
          state: present
      - name: Start the service
        ansible.builtin.service:
          name: mariadb
          enabled: yes
          state: started
      - name: Install python
        ansible.builtin.package:
          name: python3-PyMySQL
          state: present
      - name: Create a database
        mysql_db:
          name: "{{eman}}"
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
      - name: Create a user
        mysql_user:
          name: "{{resu}}"
          password: "{{ssap}}"
          priv: '*.*:ALL'
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
      - name: Debug1
        debug:
          var: ssap
      - name: Debug2
        debug:
          var: resu
      - name: Debug3
        debug:
          msg: "The database named {{eman}} is created"
