  - name: Variable in mariadb
    hosts: node1
    vars:
      village: dolakpur  # this is variable declaration you can use any variable as your choice
      people: 
        - raju
        - jaggu
        - chutki
      power: ladoo
    tasks:
      - name: Install mariadb
        ansible.builtin.package:
          name: mariadb-server
          state: present
      - name: Start the service
        ansible.builtin.service:
          name: mariadb
          enabled: yes
          state: started
      - name: Install python
        ansible.builtin.package:
          name: python3-PyMySQL
          state: present
      - name: Create a database
        mysql_db:
          name: "{{village}}"
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
      - name: Create a user
        mysql_user:
          name: "{{ item }}"
          password: "{{power}}"
          priv: '*.*:ALL'
          state: present
          login_unix_socket: /var/lib/mysql/mysql.sock
        loop: "{{people}}"
        register: output   # To register or view the details of the current task by calling in debug
      - name: Debug1
        debug:
          var: output
      - name: Debug2
        debug:
          var: people
      - name: Debug3
        debug:
          msg: "The database named {{village}} is created"
