  - name: Creating a website
    hosts: group1
    tasks:
      - name: Install nginx
        package:
          name: nginx
          state: present
      - name: Enable and start the service
        systemd:
          name: nginx
          enabled: yes
          state: started
      - name: Copying the HTML and CSS files
        copy:
          src: /home/bavin/rough/css1/
          dest: /usr/share/nginx/html
      - name: Service restart
        service:
          name: nginx
          state: restarted
