  - name: Create web page using httpd
    hosts: node1
    tasks:
      - name: Install httpd
        package:
          name: httpd
          state: present
      - name: Start httpd
        service:
          name: httpd
          enabled: yes
          state: started
      - name: Copy file CSS files
        copy:
          src: /home/bavin/rough/css1/
          dest: /var/www/html/
        register: process    #this is to check the datailed view of the process this command will be called in the last task by debug. "process" here represent as variable
      - name:
        service:
          name: httpd
          state: restarted
      - name: Add http to the firewall
        firewalld:
          service: http
          permanent: yes
          state: enabled
      - name:
        service:
          name: firewalld
          state: restarted
      - name:
        debug:
          var: process # this is called as referred in the copy task register
