  - name: Using when decision making
    hosts: group1
    tasks:
      - name: Debug
        debug:
          msg: "This tasks run in only alma linux"
        when:
          - ansible_distribution == "AlmaLinux" or ansible_distribution_major_version == "24"
